spring:
  application:
    name: spotlink

  datasource:
    url: jdbc:postgresql://localhost:5432/spotlink
    username: postgres
    password: user01
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true # JPA가 실행한 SQL문 출력력
    hibernate:
      ddl-auto: update # 엔티티 클래스 기준 DB 테이블 자동 생성/업데이트트
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true # 어떤 엔티티인지 표시
        type:
          descriptor:
            sql:
              BasicBinder: TRACE # 값 출력

  servlet:
    encoding:
      force-response: true
      charset: UTF-8
      enabled: true
  
  logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


server:
  port: 8080
