name: Spring Boot Build with Gradle Cache

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Cache Gradle files
        uses: actions/cache@v4.2.3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-cache-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-cache-${{ runner.os }}-

      - name: Build Spring Boot (skip tests)
        run: |
          echo "[2] Start Gradle build (skip tests)"
          START=$(date +%s)
          ./gradlew build -x test
          END=$(date +%s)
          echo "⏱️ Build time: $((END - START)) seconds"
